controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 100

  orientation_controller:
    type: rm_orientation_controller/Controller
    publish_rate: 100
    name: "gimbal_imu"
    frame_source: "odom"
    frame_target: "base_link"

  gimbal_controller:
    type: rm_gimbal_controllers/Controller
    controllers:
      yaw:
        joint: "yaw_joint"
        pid: { p: 0.3, i: 20, d: 0.0, i_clamp_max: 0.2, i_clamp_min: -0.2, antiwindup: true, publish_state: false }
        pid_pos: { p: 20.0, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: false }
        chassis_comp_a: 0.0
        chassis_comp_b: 0.0
        chassis_comp_c: 0.0
        chassis_comp_d: 0.0
        k_v: 1.0
        accel: 28.0
      pitch:
        joint: "pitch_joint"
        pid: { p: 0.45, i: 16, d: 0.0, i_clamp_max: 0.1, i_clamp_min: -0.1, antiwindup: true, publish_state: true }
        pid_pos: { p: 15.0, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
        k_v: 1.0
        accel: 40.0
    delay: 0.03
    chassis_vel:
      num_data: 30
      debug: true
    imu_name: "gimbal_imu"
    feedforward:
      gravity: 6.725
      enable_gravity_compensation: false
      mass_origin: [ 0.0363,0.0,0.01 ]
    bullet_solver:
      resistance_coff_qd_10: 0.001
      resistance_coff_qd_15: 0.001
      resistance_coff_qd_16: 0.001
      resistance_coff_qd_18: 0.001
      resistance_coff_qd_30: 0.001
      g: 9.81
      delay: 0.035
      wait_next_armor_delay: 0.0
      wait_diagonal_armor_delay: 0.0
      dt: 0.001
      timeout: 0.5
      publish_rate: 50
      max_switch_angle: 50
      min_switch_angle: 2
      ban_shoot_duration: 0.035
      gimbal_switch_duration: 0.09
      max_track_target_vel: 10.0
      switch_hysteresis: 1.0
      max_chassis_angular_vel: 12.0
      track_rotate_target_delay: 0.03
      track_move_target_delay: 0.04

  gimbal_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ pitch_joint_motor ]
    velocity:
      joint: pitch_joint
      search_velocity: 6.28
      vel_threshold: 1e-2
      pid: { p: 0.3, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }

  trigger_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ trigger_joint_motor ]
    velocity:
      joint: trigger_joint
      search_velocity: 3.1415
      vel_threshold: 0.2
      pid: { p: 0.3, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }

  shooter_controller:
    type: rm_shooter_controllers/Controller
    publish_rate: 50
    friction:
      friction_left:
        left_friction_wheel:
          joint: "left_friction_wheel_joint"
          pid: { p: 0.0007, i: 0.005, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: false }
          wheel_speed_direction: 1.0
      friction_right:
        right_friction_wheel:
          joint: "right_friction_wheel_joint"
          pid: { p: 0.0007, i: 0.005, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: false }
          wheel_speed_direction: -1.0
    trigger:
      joint: "trigger_joint"
      pid: { p: 36.0, i: 0.0, d: 0.4, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true, publish_state: false }
    push_per_rotation: 8
    push_qd_threshold: 0.90
    block_effort: 2.2
    block_speed: 0.1
    block_duration: 0.05
    block_overtime: 0.5
    anti_block_angle: 0.46
    anti_block_threshold: 0.1
    forward_push_threshold: 0.28
    exit_push_threshold: 0.3
    wheel_speed_drop_threshold: 3.3
    wheel_speed_raise_threshold: 1.4
    freq_threshold: 15.0

  chassis_controller:
    type: rm_chassis_controllers/BipedalController
    # ChassisBase
    publish_rate: 100
    enable_odom_tf: true
    publish_odom_tf: true
    power:
      effort_coeff: 1.339
      vel_coeff: 0.016
      power_offset: 0
    twist_angular: 0.5233
    max_odom_vel: 10.0
    timeout: 0.1
    pid_follow: { p: 5.0, i: 0, d: 0.7, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    pid_block_error: { p: 0, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    twist_covariance_diagonal: [ 0.001, 0.001, 0.001, 0.001, 0.001, 0.001 ]

    # BipedalController
    pid_left_leg: { p: 700.0, i: 100., d: 50, i_clamp_max: 20.0, i_clamp_min: -20.0, antiwindup: true, publish_state: true }
    pid_right_leg: { p: 700.0, i: 100., d: 50, i_clamp_max: 20.0, i_clamp_min: -20.0, antiwindup: true, publish_state: true }
    pid_theta_diff: { p: 160.0, i: 0.0, d: 2.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    pid_roll: { p: 1000.0, i: 0, d: 30., i_clamp_max: 30.0, i_clamp_min: -30.0, antiwindup: true, publish_state: true }
    #    pid_yaw_pos: { p: 2.0, i: 1.0, d: 0.0, i_clamp_max: 3.0, i_clamp_min: 3.0, antiwindup: true, publish_state: true }
    pid_yaw_pos: { p: 0.0, i: 0.0, d: 0.0, i_clamp_max: 3.0, i_clamp_min: 3.0, antiwindup: true, publish_state: true }
    pid_yaw_vel: { p: 0.4, i: 1.5, d: 0., i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true, publish_state: true }
    pid_left_leg_theta: { p: 50.0, i: 0., d: 3., i_clamp_max: 2.0, i_clamp_min: -2.0, antiwindup: true, publish_state: true }
    pid_right_leg_theta: { p: 50.0, i: 0., d: 3., i_clamp_max: 2.0, i_clamp_min: -2.0, antiwindup: true, publish_state: true }
    pid_left_leg_theta_vel: { p: 6.0, i: 3.0, d: 0., i_clamp_max: 10.0, i_clamp_min: -10.0, antiwindup: true, publish_state: true }
    pid_right_leg_theta_vel: { p: 6.0, i: 3.0, d: 0., i_clamp_max: 10.0, i_clamp_min: -10.0, antiwindup: true, publish_state: true }
    pid_left_wheel_vel: { p: 0.1, i: 0.01, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
    pid_right_wheel_vel: { p: 0.1, i: 0.01, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }

    pid_left_leg_stand_up: { p: 600.0, i: 0.0, d: 30.0, i_clamp_max: 20.0, i_clamp_min: -20.0, antiwindup: true, publish_state: true }
    pid_right_leg_stand_up: { p: 600.0, i: 0.0, d: 30.0, i_clamp_max: 20.0, i_clamp_min: -20.0, antiwindup: true, publish_state: true }

    gravity_force: 130
    spring_force: 0
    default_leg_length: 0.2
    L_weight: 0.53
    Lm_weight: 0.47
    # 机体质心距离转轴位置
    l: 0.04
    # 轮子质量
    m_w: 0.563518
    # 摆杆质量
    #    m_p: 1.554
    m_p: 1.068
    # 机体质量
    M: 20
    # 轮子转动惯量
    i_w: 0.0010134
    #    i_w: 0.002028
    # 摆杆转动惯量
    #    i_p: 0.0029816
    i_p: 0.01316
    # 机体转动惯量
    i_m: 0.2467

    g: 9.81
    # 轮子半径
    wheel_radius: 0.06

    # theta d_theta x dx phi d_phi
    q: [ 100.0, 1, 1000.0, 100, 5025.0, 1 ]
    r: [ 55, 2.0 ]

    x_bias: 0.06
    theta_bias: 0.09
    pitch_bias: -0.0
    roll_bias: 0.

    # under_lower_threshold: -M_PI / 2 + 0.7
    under_lower_threshold: -0.8708
    # under_upper_threshold: M_PI / 2 - 1.4
    under_upper_threshold: 0.1708
    # front_lower_threshold: -M_PI / 2 + 0.7
    front_lower_threshold: -0.8708
    # front_upper_threshold: M_PI - 0.5
    front_upper_threshold: 2.6416
    # behind_lower_threshold: M_PI / 2 - 1.4
    behind_lower_threshold: 0.1708
    # behind_upper_threshold: M_PI - 0.5
    behind_upper_threshold: 2.6416
    # upstair_exit_threshold: M_PI_2 - 0.65
    upstair_exit_threshold: 0.9208
    # upstair_des_theta: M_PI_2 - 0.6
    upstair_des_theta: 0.9708

    jumpOverTime: 2.0
    p1: -241100
    p2: 170300
    p3: 39310
    p4: 3234
