controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 100

  orientation_controller:
    type: rm_orientation_controller/Controller
    publish_rate: 100
    name: "gimbal_imu"
    frame_source: "odom"
    frame_target: "base_link"

  gimbal_controller:
    type: rm_gimbal_controllers/Controller
    controllers:
      yaw:
        joint: "yaw_joint"
        pid: { p: 0.7, i: 15.0, d: 0.0, i_clamp_max: 0.1, i_clamp_min: -0.1, antiwindup: true, publish_state: false }
        pid_pos: { p: 23.0, i: 0, d: 0.1, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: false }
        chassis_comp_a: 0.00651
        chassis_comp_b: 0.5085
        chassis_comp_c: 1.5708
        chassis_comp_d: 0.0736
        k_v: 1.0
        accel: 45.0
      pitch:
        joint: "pitch_joint"
        pid: { p: 0.7, i: 15.0, d: 0.0, i_clamp_max: 0.2, i_clamp_min: -0.2, antiwindup: true, publish_state: false }
        pid_pos: { p: 18.0, i: 0, d: 0.1, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: false }
        k_v: 1.0
        accel: 40.0
    delay: 0.03
    chassis_vel:
      num_data: 30
      debug: true
    imu_name: "gimbal_imu"
    feedforward:
      gravity: 8.725
      enable_gravity_compensation: false
      mass_origin: [ 0.0363,0.0,0.01 ]
    bullet_solver:
      resistance_coff_qd_10: 0.001
      resistance_coff_qd_15: 0.001
      resistance_coff_qd_16: 0.001
      resistance_coff_qd_18: 0.001
      resistance_coff_qd_30: 0.001
      g: 9.81
      delay: 0.035
      wait_next_armor_delay: 0.0
      wait_diagonal_armor_delay: 0.0
      dt: 0.001
      timeout: 0.5
      publish_rate: 50
      max_switch_angle: 50
      min_switch_angle: 2
      ban_shoot_duration: 0.035
      gimbal_switch_duration: 0.09
      max_track_target_vel: 10.0
      switch_hysteresis: 1.0
      max_chassis_angular_vel: 12.0
      track_rotate_target_delay: 0.03
      track_move_target_delay: 0.04

  gimbal_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ pitch_joint_motor ]
    velocity:
      joint: pitch_joint
      search_velocity: 6.28
      vel_threshold: 1e-2
      pid: { p: 0.3, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }

  trigger_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ trigger_joint_motor ]
    velocity:
      joint: trigger_joint
      search_velocity: 3.1415
      vel_threshold: 0.2
      pid: { p: 0.3, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }

  shooter_controller:
    type: rm_shooter_controllers/Controller
    publish_rate: 50
    friction:
      friction_left:
        left_friction_wheel:
          joint: "left_friction_wheel_joint"
          pid: { p: 0.0007, i: 0.005, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: false }
          wheel_speed_direction: 1.0
      friction_right:
        right_friction_wheel:
          joint: "right_friction_wheel_joint"
          pid: { p: 0.0007, i: 0.005, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: false }
          wheel_speed_direction: -1.0
    trigger:
      joint: "trigger_joint"
      pid: { p: 34.0, i: 0.0, d: 1.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true, publish_state: false }
    push_per_rotation: 9
    push_qd_threshold: 0.90
    block_effort: 2.2
    block_speed: 0.1
    block_duration: 0.05
    block_overtime: 0.5
    anti_block_angle: 0.46
    anti_block_threshold: 0.1
    forward_push_threshold: 0.22
    exit_push_threshold: 0.25
    wheel_speed_drop_threshold: 5.7
    wheel_speed_raise_threshold: 1.2
    freq_threshold: 15.0


  chassis_controller:
    type: rm_chassis_controllers/BipedalController
    # ChassisBase
    publish_rate: 100
    enable_odom_tf: true
    publish_odom_tf: true
    power:
      effort_coeff: 1.339
      vel_coeff: 0.016
      power_offset: 0
    twist_angular: 0.5233
    timeout: 0.1
    pid_follow: { p: 3.8, i: 0, d: 0.6, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    pid_block_error: { p: 0, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    twist_covariance_diagonal: [ 0.001, 0.001, 0.001, 0.001, 0.001, 0.001 ]

    # BipedalController
    pid_left_leg: { p: 900.0, i: 100., d: 30, i_clamp_max: 10.0, i_clamp_min: -10.0, antiwindup: true, publish_state: true }
    pid_right_leg: { p: 900.0, i: 100., d: 30, i_clamp_max: 10.0, i_clamp_min: -10.0, antiwindup: true, publish_state: true }
    pid_theta_diff: { p: 100.0, i: 0.0, d: 10.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: false }
    pid_roll: { p: 250.0, i: 10, d: 50., i_clamp_max: 30.0, i_clamp_min: -30.0, antiwindup: true, publish_state: false }
    pid_yaw_vel: { p: 10.0, i: 0.1, d: 0., i_clamp_max: 3.0, i_clamp_min: 3.0, antiwindup: true, publish_state: true }
    pid_left_leg_theta: { p: 10.0, i: 0., d: 0., i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true, publish_state: true }
    pid_right_leg_theta: { p: 10.0, i: 0., d: 0., i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true, publish_state: true }
    pid_left_wheel_vel: { p: 0.05, i: 0.001, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true, publish_state: true }
    pid_right_wheel_vel: { p: 0.05, i: 0.001, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true, publish_state: true }

    leg_length: 0.18
    L_weight: 0.375
    Lm_weight: 0.825
    # 机体质心距离转轴位置
    l: 0.03
#    l: 0.001
    # 轮子质量
#    m_w: 0.803567
    m_w: 0.123518
    # 摆杆质量
    m_p: 0.309603
#    m_p: 0.2467
    # 机体质量
    M: 12.0
    # 轮子转动惯量
#    i_w: 0.003357
    i_w: 0.0003094
    # 摆杆转动惯量
    i_p: 0.0021406
    # 机体转动惯量
    i_m: 0.1018
#    i_m: 0.1748
    g: 9.81
    # 轮子半径
#    wheel_radius: 0.09
    wheel_radius: 0.055

    # theta d_theta x dx phi d_phi
#    q: [ 300., 8., 5., 100., 1050., 5. ]
    #    q: [ 100., 15., 500., 1., 1050., 10. ]
    q: [ 400.0, 10, 1000, 1, 5000.0, 1 ]
    #    q: [ 100., 10., 1., 1., 5000., 10. ]
    # T Tp
#    r: [ 0.6, 0.2 ]
#    r: [ 10, 25 ]
    r: [ 125 , 25 ]
